[package]
name = "example"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
regex = { version = "1.10.4" }
lazy_static = { path = "../lazy-static" }
regex = "0.2"
